#!/usr/bin/env bash

read  -n 1 -p "Project Name:" projectName

echo 'creating $projectName';

#if [ "$1" == "clone" ]; then
#  git clone https://github.com/marcneubauer/Magento2.git $projectName && cd $projectName;
#fi
#
#echo "---------------======= Magecif repo status ========-------------------------" \
#&& git log --graph --boundary '--format=%C(yellow)%h%Creset%C(bold cyan)%d%Creset %s %C(dim normal)(%ar)%Creset' --all -42 \
#&& git status \
#
##git config --global core.autocrlf false
##git config --global core.eol LF
##git config --global core.fileMode false
##git config --global diff.renamelimit 5000
#
#sudo chmod u+x ./*
#
#
#echo "---------------======= Pulling Image ========-------------------------" \
#
#docker image pull rafaelcgstz/magento2
#
#if [ "$(uname)" == "Darwin" ]; then
#  git checkout -f mac;
#  sed -i '' -e "s/<project_name>/$projectName/g" docker-compose.yml \
#  && sed -i '' -e "s/<project_name>/$projectName/g" docker-compose-dev.yml \
#  && sed -i '' -e "s/<project_name>/$projectName/g" docker-sync.yml
#else
#  git checkout -f master;
#  sed -i '' -e "s/<project_name>/$projectName/g" docker-compose.yml;
#fi
#
#if [ ! -e src/index.php ]; then
#  echo "<?php phpinfo();" > src/index.php;
#fi
#
#if [ -d src/app/etc ]; then
#  if [ ! -e src/app/etc/env.php ]; then
#    cp .docker/users/env.sample.php src/app/etc/env.php;
#  fi
#fi
#
#chmod -R 777 src
#
#bash start
