#!/usr/bin/env bash

read  -p "Project Name:" projectName

sudo chmod u+x ./*

echo "---------------======= Creating Project: $projectName ===------------------"; \

#if [ "$1" == "clone" ]; then
#  git clone https://github.com/marcneubauer/Magento2.git $projectName && cd $projectName;
#fi

git log --graph --boundary '--format=%C(yellow)%h%Creset%C(bold cyan)%d%Creset %s %C(dim normal)(%ar)%Creset' --all -42 \
&& echo "---------------======= Local git status ========-------------------------" \
&& git status \

#git config --global core.autocrlf false
#git config --global core.eol LF
#git config --global core.fileMode false
#git config --global diff.renamelimit 5000

echo "-------------------======= Pulling Image ========-------------------------" \

docker image pull rafaelcgstz/magento2

# apply project name to config files
if [ "$(uname)" == "Darwin" ]; then
#  if on a mac, checkout mcif branch based off origin/mac
  git checkout -f mcif;
# sprinkle around project name captured at top
  sed -i '' -e "s/<project_name>/$projectName/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$projectName/g" docker-compose-dev.yml \
  && sed -i '' -e "s/<project_name>/$projectName/g" docker-sync.yml \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./start \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./installcifmodule \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./.docker/bin/install-magento2 \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./.docker/config/magento.conf \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./dumpdb \
  && sed -i '' -e "s/<project_name>/$projectName/g" ./importdb
else
# else, good luck bro
  git checkout -f master;
  sed -i '' -e "s/<project_name>/$projectName/g" docker-compose.yml;
fi

# if initial init then copy across default phpinfo index.php
if [ ! -d src/ ]; then
  mkdir src;
fi
if [ ! -f src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

# copy in local app/etc/env.php? again not sure about this
#if [ -d src/app/etc ]; then
#  if [ ! -e src/app/etc/env.php ]; then
#    cp .docker/users/env.sample.php src/app/etc/env.php;
#  fi
#fi

chmod -R 777 src

bash start
