#!/usr/bin/env bash

#aggravatedservices="../commerce-cif-magento-extension/AggregatedServices";
aggravatedservices="commerce-cif-magento-extension/AggregatedServices";
projectname="<project_name>"

# clone cif extension into local dir
echo "Cloning CIF Module locally";
git clone https://github.com/adobe/commerce-cif-magento-extension.git commerce-cif-magento-extension/

dockerdo() {
    docker exec -i ${projectname}_apache_1 /bin/bash -c "$1"
}

if [ -d src/app/code/Magento ]; then
  if [ -d ${aggravatedservices} ]; then
    echo "Copying commerce-cif-magento-extension/AggregatedServices into src";
    #ln -s ${aggravatedservices}  src/app/code/Magento;
    cp -R ${aggravatedservices}  src/app/code/Magento;
    echo "Enabling Module";echo ""
    dockerdo "magento module:enable Magento_AggregatedServices"
    dockerdo "magento setup:upgrade"
    dockerdo "magento setup:di:compile"
    dockerdo "magento setup:static-content:deploy -f"
    echo "";echo ""
  fi
fi
