#!/usr/bin/env bash

#aggravatedservices="../commerce-cif-magento-extension/AggregatedServices";
aggravatedservices="backup/commerce-cif-magento-extension/AggregatedServices";

dockerdo() {
    docker-compose exec --user www-data apache /usr/bin/env bash -c "$1"
}

if [ ! -d ${aggravatedservices} ]; then
    # clone cif extension into local dir
    echo "Cloning CIF Module locally.";
    git clone https://github.com/adobe/commerce-cif-magento-extension.git backup/commerce-cif-magento-extension/
fi

if [ -d src/app/code/Magento ]; then
  if [ -d ${aggravatedservices} ]; then
    echo "Copying commerce-cif-magento-extension/AggregatedServices into src/.";
    #ln -s ${aggravatedservices}  src/app/code/Magento;
    cp -R ${aggravatedservices}  src/app/code/Magento \
    && echo "Enabling Module";echo "" \
    && dockerdo "/var/www/html/bin/magento cache:clean" \
    && dockerdo "/var/www/html/bin/magento setup:upgrade" \
    && dockerdo "/var/www/html/bin/magento module:enable Magento_AggregatedServices" \
    && dockerdo "/var/www/html/bin/magento setup:di:compile" \
    && dockerdo "/var/www/html/bin/magento setup:static-content:deploy -f" \
    && dockerdo "/var/www/html/bin/magento cache:clean"
    echo "";echo ""
  else
    echo "AggregatedServices Module not found?"
  fi
else
    dockerdo "ls -al" \
    && echo "Magento is not yet installed."
    echo "";echo ""
fi
