#!/usr/bin/env bash

echo "---------=======Starting Containers========---------"

sudo ifconfig lo0 alias 10.254.254.254

docker-sync start && \

docker-compose up -d && \

#docker-compose -p <project_name> up -d && \

version=$(git describe --tags $(git rev-list --tags --max-count=1))

echo "
===================== 🚀 Done 🚀 ===================

      Created by Rafael Corrêa Gomes
      v.$version
      Access your new links:

      🌎 Web server: http://www.<project_name>.com/
      ⚙️ PHPMyAdmin: http://www.<project_name>.com:8080
      ✉️ Local emails: http://www.<project_name>.com:8025

===================== 🚀 Done 🚀 ==================="
#&& git status;
